version: "3.8"
services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: iot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

volumes:
  mongodb_data:
